### ISSUE TITLE
Use minar with 16 bit timer?

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/minar-platform-mbed#13]
Because of HW limitations, we need to use a 16bit timer for minar.

Is this possible as is? Has this been done by someone before? What would be the changes required and what would be the limitations?

**Comment by 0xc0170** [comment]
Hi Markus,

I am curious what timer peripheral did you choose for low power ticker. I know some RTC have 24bit counters, but I haven't seen yet 16bit counter.

The requirement is to provide 32bit counter. This does not mean this is hw requirement. You can count overflows to extend the 16bit counter to 32bit. Don't forget then to shift properly counter overflow (as that one shall be also 32bit). Does that answer your question?

There will be a documentation for low power ticker to capture this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2090

**Comment by 0xc0170** [comment]
I forgot to pinpoint the code reference, nrf51 contains 24bit RTC counter, where we do what I described the above. Look at https://github.com/ARMmbed/mbed-hal-nrf51822-mcu/blob/master/source/us_ticker.c#L137

**Comment by 0xc0170** [comment]
@markus-becker-tridonic-com Does that answer your question?

**Comment by 0xc0170** [comment]
Please reopen if further questions, or the comments above did not address it fully.

**Comment by markus-becker-tridonic-com** [comment]
@bcostm would this be what we are looking for?
